name: disaster_relief_coordination
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  flutter_svg: ^2.0.7
  email_sender: ^2.1.0
  mailer: ^6.0.0
  shared_preferences: ^2.5.3
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  firebase_storage: ^13.0.1
  cloud_firestore: ^6.0.1
  fluttertoast:  ^8.0.9
  font_awesome_flutter : ^10.3.0
  http: ^1.2.2
  xml: ^6.5.0
  flutter_map: ^6.1.0
  maplibre_gl: ^0.22.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.9

flutter:

  uses-material-design: true

  assets:
      - assets/image/
      - assets/ico/
      - assets/fonts/


  fonts:
    - family: GoogleSansCode
      fonts:
          - asset: assets/fonts/GoogleSansCode-Regular.ttf
            weight: 400
          - asset: assets/fonts/GoogleSansCode-Bold.ttf
            weight: 700


